version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres-cripto
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: cripto
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
